#ifndef C_PART_03
#define C_PART_03

#include "library.h"

void part_three(void)
{
    printf("Chapter three from Zlatopolskiy.\n\n");
    printf("Boolean true = %d, false = %d, sizeof = %d \n", true, false, sizeof (bool));
    printf("\nTask 3.1\n");
    bool a = true;
    bool b = false;
    bool c = false;
    bool r = a || b;
    printf("a) A or B = %d or %d = %d\n", a, b, r);
    r = a && b;
    printf("b) A and B = %d and %d = %d\n", a, b, r);
    r = b || c;
    printf("c) B or C = %d or %d = %d\n", b, c, r);
    printf("\nTask 3.3\n");
    a = true; b = false; c = false;
    r = !a || b;
    printf("a) not A or B = not %d or %d = %d\n", a, b, r);
    r = a || !b;
    printf("b) A or not B = %d or not %d = %d\n", a, b, r);
    r = (a && b) || c;
    printf("c) (A and B) or C = %d and %d or %d = %d\n", a, b, c, r);
    printf("\nTask 3.5\n");
    a = true; b = false; c = false;
    r = a || (b && !c);
    printf("a) A or (B and not C) = %d or (%d and not %d) = %d\n", a, b, c, r);
    r = !a && !b;
    printf("b) not A and not B = not %d and not %d = %d\n", a, b, r);
    r = !(a && c) || b;
    printf("v) not (A and C) or B = not (%d and %d) or %d = %d\n", a, c, b, r);
    r = (a && !b) || c;
    printf("g) A and not B or C = %d and not %d or %d = %d\n", a, b, c, r);
    r = a && (!b || c);
    printf("d) A and (not B or C) = %d and (not %d or %d) = %d\n", a, b, c, r);
    r = a || (!(b && c));
    printf("e) A or (not(B and C)) = %d or (not (%d and %d)) = %d\n", a, b, c, r);
    printf("\nTask 3.7\n");
    a = true; b = false; c = false;
    r = a || !(a && b) || c;
    printf("a) A or not (A and B) or C = %d or not(%d and %d) or %d = %d\n", a, a, b, c, r);
    r = !a || (a && (b || c));
    printf("b) not A or (A and (B  or C)) = not %d or (%d and (%d or %d)) = %d\n", a, a, b, c, r);
    r = (a || (b && !c)) && c;
    printf("v) (A or (B and not C)) and C = (%d or (%d and not %d)) and %d = %d\n", a, b, c, c, r);
    printf("\nTask 3.9\n");
    bool x = true;
    bool y = false;
    bool z = false;
    r = !x || !y || !z;
    printf("a) not X or not Y or not Z = not %d or not %d or not %d = %d\n", x, y, z, r);
    r = (!x || !y) && (x || y);
    printf("b) (not X or not Y) and (X or Y) = (not %d or not %d) and (%d or %d) = %d\n", x, y, x, y, r);
    r = (x && y) || (x && z) || !z;
    printf("v) (X and Y) or (X and Y) or not Z = (%d and %d) or (%d and %d) or not %d = %d\n", x, y, x, y, z, r);
    printf("\nTask 3.12\n");
    int x_i = 2;
    int y_i = 2;
    r = (x_i >= 0) && (y_i*y_i > 4);
    printf("v) (X >= 0) and (Y^2 > 4) = (%d >= 0) and (%d^2 > 4) = %d\n", x_i, y_i, r);
    x_i = 1;
    y_i = 2;
    r = (x_i * y_i != 4) && (y_i > x_i);
    printf("g) (X * Y != 4) and (Y > X) = (%d * %d != 4) and (%d > %d) = %d.\n", x_i, y_i, y_i, x_i, r);
    x_i = 1;
    y_i = 2;
    r = (!(x_i * y_i < 1)) && (y_i > x_i);
    printf("e) (not(X * Y < 1)) and (Y > X) = (not(%d * %d < 1)) and (%d > %d) = %d.\n", x_i, y_i, y_i, x_i, r);
    printf("\nTask 3.14\n");
    x_i = 1;
    y_i = 0;
    r = !(x_i || y_i);
    printf("a)not(X or Y) = not(%d or %d) = %d.\n", x_i, y_i, r);
    x_i = 1;
    y_i = 0;
    r = !x_i && y_i;
    printf("b)not X and Y = not %d and %d = %d.\n", x_i, y_i, r);
    x_i = 0;
    y_i = 1;
    r = x_i && !y_i;
    printf("v)X and not Y = %d and not %d = %d.\n", x_i, y_i, r);
    printf("\nTask 3.17\n");
    int a_i = 1;
    int b_i = 0;
    r = (!a_i && !b_i) || a_i;
    printf("a)not A and B or A = not %d and %d or %d = %d.\n", a_i, b_i, a_i, r);
    a_i = 0;
    b_i = 1;
    r = b_i || (!a_i && !b_i);
    printf("b)B or not A and B =  %d or not %d and %d = %d.\n", b_i, a_i, b_i, r);
    a_i = 1;
    b_i = 0;
    r = b_i && !(a_i && !b_i);
    printf("v)B and not (A or not B) = %d and not (%d or not %d) = %d.\n", b_i, a_i, b_i, r);
    printf("\nTask 3.20\n");
    x_i = 0;
    y_i = 1;
    r = !(!x_i || y_i) || !x_i;
    printf("a)not(not X or Y) or X =  not(not %d or %d) or not %d = %d.\n", x_i, y_i, x_i, r);
    x_i = 1;
    y_i = 0;
    r = !(!x_i && !y_i) && x_i;
    printf("b)not(not X and not Y) and X = not(not %d and not %d) and %d = %d.\n", x_i, y_i, x_i, r);
    x_i = 0;
    y_i = 1;
    r = !(x_i || !y_i) || !y_i;
    printf("v)not(X or not Y) or not Y = not(%d or not %d) or not %d = %d.\n", x_i, y_i, y_i, r);
    printf("\nTask 3.23\n");
    a_i = 0;
    b_i = 1;
    int c_i = 1;
    r = !(a_i || (!b_i && c_i)) || c_i;
    printf("a)r = not(%d or (not %d and %d)) or %d = %d.\n", a_i, b_i, c_i, c_i, r);
    a_i = 1; b_i = 0; c_i = 1;
    r = !((a_i && !b_i) || c_i) && b_i;
    printf("b)r = not((%d and not %d) or %d) and %d = %d.\n", a_i, b_i, c_i, b_i, r);
    a_i = 0; b_i = 1; c_i = 0;
    r = !(!a_i || (b_i && c_i)) || a_i;
    printf("v)r = not(not %d or (%d and %d)) or %d = %d.\n", a_i, b_i, c_i, a_i, r);
    printf("\nTask 3.26\n");
    x_i = 0; y_i = 1;
    int z_i = 0;
    r = !(x_i || y_i) && (!x_i || !z_i);
    printf("a)r = not(%d or %d) and (not %d or not %d) = %d.\n", x_i, y_i, x_i, z_i, r);
    x_i = 1; y_i = 0; z_i = 1;
    r = !(!x_i && y_i) || (x_i && !z_i);
    printf("b)r = not(not %d and %d) or (%d and not %d) = %d.\n", x_i, y_i, x_i, z_i, r);
    x_i = 0; y_i = 1; z_i = 1;
    r = x_i || (!y_i && !(x_i || !z_i));
    printf("v)r = %d or not (%d and not (%d or not %d)) = %d.\n", x_i, y_i, x_i, z_i, r);
    printf("\nTask 3.28\n");
    a_i = 79; b_i = 132; c_i = 35;
    printf("Check some statements, A = %d, B = %d, C = %d.\n", a_i, b_i, c_i);
    r = (a_i > 100) && (b_i > 100);
    printf("a)A > 100 and B > 100 = %d.\n", r);
    r = (a_i % 2 == 0) ^ (b_i % 2 == 0);
    printf("b)A or B - even = %d.\n", r);
    r = (a_i > 0) || (b_i > 0);
    printf("v)A or B - positive = %d.\n", r);
    r = (a_i % 3 == 0) && (b_i % 3 == 0) && (c_i % 3 == 0);
    printf("g)A, B, C devided by 3 = %d.\n", r);
    r = (((a_i < 50) + (b_i < 50) + (c_i < 50)) == 1);
    printf("d)Only one A,B,C less < 50 = %d.\n", r);
    r = (a_i < 0) || (b_i < 0) || (c_i < 0);
    printf("e)At least one A,B,C less < 0 = %d.\n", r);
    printf("\nTask 3.30\n");
    a_i = 8;
    r = (a_i % 2 == 0) || (a_i % 3 == 0);
    printf("a)A = %d, devided by 2 or 3 = %d.\n", a_i, r);
    a_i = 10;
    r = (a_i % 3 != 0 && a_i % 10 == 0);
    printf("b)When integer A = %d, is not a multiple of 3 and ends with 0. Result = %d.\n", a_i, r);
    printf("\nTask 3.32\n");
    double x_d = -7, y_d = 3;
    r = x_d <= -2 && y_d >= 1;
    printf("a)Graphics, result = %d.\n", r);
    x_d = 3.0; y_d = 1.0;
    r = y_d <= 1.5 && y_d >= -2;
    printf("b)Graphics, result = %d.\n", r);
    x_d = 2.0; y_d = 3.0;
    r = x_d >= 1.0 && x_d <= 2.0 && y_d <= 4.0;
    printf("v)Graphics, result = %d.\n", r);
    x_d = 2.5; y_d = 3.0;
    r = x_d >= 1.0 && y_d >= 2.0 && y_d <= 4.0;
    printf("g)Graphics, result = %d.\n", r);
    x_d = 3.5; y_d = 1.0;
    r = (x_d >= 1 && y_d <= -1) || (x_d >= 2 && y_d >= 0);
    printf("d)Graphics, result = %d.\n", r);
    x_d = 2.5; y_d = 2.0;
    r = x_d >= 2 && (y_d >= 1 || y_d <= -1.5);
    printf("e)Graphics, result = %d.\n", r);
    x_d = 1.5; y_d = -1.5;
    r = x_d >= 1 && x_d <= 3 && y_d <= -1 && y_d >= -2;
    printf("j)Graphics, result = %d.\n", r);
    x_d = 3.5; y_d = 1.0;
    r = (x_d >= 2) || (y_d >= 0.5 && y_d <= 1.5);
    printf("z)Graphics, result = %d.\n", r);
    printf("\nTask 3.34\n");
    int h_1 = 3, v_1 = 5, h_2 = 6, v_2 = 5;
    r = h_1 == h_2 || v_1 == v_2;
    printf("a)Rook on H = %d, V = %d, Can attack pawn at H = %d, V = %d. Result = %d\n", h_1, v_1, h_2, v_2, r);
    h_1 = 3, v_1 = 4, h_2 = 1, v_2 = 2;
    r = (abs(h_2 - h_1) == abs(v_2 - v_1));
    printf("b)Bishop on H = %d, V = %d, Can attack pawn at H = %d, V = %d. = %d\n", h_1, v_1, h_2, v_2, r);
    h_1 = 3, v_1 = 4, h_2 = 1, v_2 = 2;
    r = abs(h_2 - h_1) <= 1 && abs(v_2 - v_1) <= 1;
    printf("v)King on H = %d, V = %d, Can move to H = %d, V = %d. = %d.\n", h_1, v_1, h_2, v_2, r);
    r = (abs(h_2 - h_1) == abs(v_2 - v_1)) || ((h_1 == h_2) || (v_1 == v_2));
    printf("g)Queen on H = %d, V = %d, Can move to H = %d, V = %d. = %d.\n", h_1, v_1, h_2, v_2, r);
    printf("\nTask 3.35\n");
    int h_3 = 2, v_3 = 5;
    h_1 = 2; v_1 = 2; h_2 = 7; v_2 = 5;
    r = (h_1 == h_3 || v_1 == v_3) && (h_2 != h_3 && v_2 != v_3);
    printf("a)Rook A [%d,%d], move to [%d,%d] and Rook B [%d,%d] = %d.\n", h_1, v_1, h_3, v_3, h_2, v_2, r);
    h_1 = 3, v_1 = 3; h_3 = 7; h_2 = 6; v_2 = 7; v_3 = 3;
    r = (h_1 == h_3 || v_1 == v_3);
    r = r && !(abs(h_1 - h_2) == 2 && abs(v_1 - v_2) == 1);
    r = r && !(abs(h_1 - h_2) == 1 && abs(v_1 - v_2) == 2);
    printf("v)Rook A [%d,%d], move to [%d,%d] and Knight B [%d,%d] = %d.\n", h_1, v_1, h_3, v_3, h_2, v_2, r);
}


#endif //Part 03.

